projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4444"
  prisma:
    schemaPath: "src/generated/prisma.graphql"
    image: "prismagraphql/prisma:1.34.10"
    extensions:
      prisma: prisma.yml
    # codegen:
    #   - generator: prisma-binding
    #     language: typescript
    #     output:
    #       binding: src/generated/prisma.ts
