const emailList = [
  {
    name: "Joan",
    surname: "Loughrey",
    email: "joan.loughrey@qub.ac.uk",
    linkedin:
      "https://www.linkedin.com/in/joan-loughrey-439aa760/?originalSubdomain=uk",
    comment: "Professor Joan Loughrey",
    firm: "Queen's University Belfast",
    source: "https://www.qub.ac.uk/schools/SchoolofLaw/people/administrative/",
    sentEmailsTime: [],
  },
  {
    name: "Colette",
    surname: "Farrell",
    email: "c.a.farrell@qub.ac.uk",
    linkedin:
      "https://www.linkedin.com/in/colette-farrell-5605a0273/?originalSubdomain=uk",
    comment: "School Manager",
    firm: "Queen's University Belfast",
    sentEmailsTime: [],
  },
  {
    name: "Michelle",
    surname: "Madden",
    email: "M.Madden@qub.ac.uk",
    linkedin: "",
    comment: "Head of School Secretary",
    firm: "Queen's University Belfast",
    sentEmailsTime: [],
  },
  {
    name: "Deirdre",
    surname: "Timoney",
    email: "D.Timoney@qub.ac.uk",
    linkedin: "",
    comment: "Employability & Placement Officer ",
    firm: "Queen's University Belfast",
    sentEmailsTime: [],
  },
  {
    name: "Eóin",
    surname: "Clarke",
    email: "E.Clarke@qub.ac.uk",
    linkedin: "",
    comment: "Student and Digital Support Officer",
    firm: "Queen's University Belfast",
    sentEmailsTime: [],
  },
  {
    name: "Kathryn",
    surname: "Larmour",
    email: "K.Larmour@qub.ac.uk",
    linkedin: "",
    comment: "Undergraduate Officer ",
    firm: "Queen's University Belfast",
    sentEmailsTime: [],
  },
  {
    name: "Angela",
    surname: "Brady",
    email: "a.brady@qub.ac.uk",
    linkedin: "",
    comment: "Postgraduate Officer ",
    firm: "Queen's University Belfast",
    sentEmailsTime: [],
  },
  {
    name: "Deveral",
    surname: "Capps",
    email: "d.capps@leedsbeckett.ac.uk",
    linkedin: "",
    comment:
      "Deveral is the Dean of Leeds Law School, joining Leeds Beckett in 2015.  As a legal academic he has taught on undergraduate, postgraduate and professional courses and published widely on legal education, legal skills and eCommerce law. ",
    firm: "University of leeds",
    sentEmailsTime: [],
  },
  {
    name: "Melissa",
    surname: "Askew",
    email: "M.Askew@leedsbeckett.ac.uk",
    linkedin: "",
    comment:
      "Melissa is Head of Law, and has overall responsibility for all of the academic Law courses at Leeds Beckett. Melissa is interested in employability for students and making sure that there are plenty of opportunities for Leeds Beckett’s Law students to make themselves attractive for future employees.",
    firm: "University of leeds",
    sentEmailsTime: [],
  },
  {
    name: "Louisa",
    surname: "Ashley",
    email: "Louisa.Ashley@leedsbeckett.ac.uk",
    linkedin: "",
    comment:
      "Louisa is Head of Subject at Leeds Law School, overseeing the School’s postgraduate provision. Research interests: Legal Skills. Please contact me if you are a prospective research student in one of the above areas if you would like to discuss your project and supervision.",
    firm: "University of leeds",
    sentEmailsTime: [],
  },
  {
    name: "TT",
    surname: "Arvind",
    email: "t.t.arvind@york.ac.uk",
    linkedin: "",
    comment: "",
    firm: "York Law School",
    sentEmailsTime: [],
  },
  {
    name: "Sara",
    surname: "Boulton",
    email: "sara.boulton@york.ac.uk",
    linkedin: "",
    comment:
      "I set up the Leeds Law School Clinic, taught Property Law and worked with the Careers and Employability team.",
    firm: "York Law School",
    sentEmailsTime: [],
  },
  {
    name: "Frank",
    surname: "Dignan",
    email: "frank.dignan@york.ac.uk",
    linkedin: "",
    comment: "Associate Lecturer (T&S) Problem Based Learning",
    firm: "York Law School",
    sentEmailsTime: [],
  },
  {
    name: "Scott",
    surname: "Slorach",
    email: "scott.slorach@york.ac.uk",
    linkedin: "",
    comment:
      "Director of Learning and Teaching. Previously, I was Vice-President (Education) and Board Member of the University of Law, and before that Professor of Curriculum Development at the law school at Nottingham Trent University.  I qualified as a solicitor with McKenna & Co (now CMS) before moving to Allen & Overy. Teaches Legal Skills and Advanced Legal Skills",
    firm: "York Law School",
    sentEmailsTime: [],
  },
  //   {
  //     name: "Aristea",
  //     surname: "Koukiadaki",
  //     email: "aristea.koukiadaki@manchester.ac.uk",
  //     linkedin: "",
  //     comment:
  //       "Professor of Labour Law and Industrial Relations & Head of Law Department",
  //     firm: "University of Manchester",
  //     sentEmailsTime: [],
  //   },
  {
    name: "Javier",
    surname: "Garcia Oliva",
    email: "",
    linkedin: "",
    comment: "Head of Law",
    firm: "University of Manchester",
    sentEmailsTime: [],
  },
  {
    name: "Clair",
    surname: "Gammage",
    email: "C.A.Gammage@exeter.ac.uk",
    linkedin: "",
    comment: "Professor, Head of School",
    firm: "University of Exeter",
    sentEmailsTime: [],
  },
  {
    name: "Daniel",
    surname: "Frost",
    email: "D.Frost@exeter.ac.uk",
    linkedin: "",
    comment: "Law School Department Manager",
    firm: "University of Exeter",
    sentEmailsTime: [],
  },
  {
    name: "Warren",
    surname: "Barr",
    email: "w.barr.1@bham.ac.uk",
    linkedin: "",
    comment: "Dean of the Law School",
    firm: "University of Birmingham",
    sentEmailsTime: [],
  },
  {
    name: "Lisa",
    surname: "Webley",
    email: "l.c.webley@bham.ac.uk",
    linkedin: "",
    comment:
      "Chair in Legal Education and Research. Professor Lisa Webley’s research concerns the regulation, education and ethicality and professionalism of the legal profession, and broader access to justice and rule of law concerns. She has been the Principal Investigator on several large research projects and has undertaken funded empirical research for public bodies and organisations including the European Commission; the Ministry of Justice and the Department for Trade and Industry. She is head of research in CEPLER.",
    firm: "University of Birmingham",
    sentEmailsTime: [],
  },
  {
    name: "Linden",
    surname: "Thomas",
    email: "l.thomas@bham.ac.uk",
    linkedin: "",
    comment:
      "Reader in Clinical Legal Education and Pro Bono Solicitor, Head of Education and Interim Head of CEPLER. She has a particular interest in pro bono, clinical legal education and public legal education and her teaching and scholarship focus on those areas. Her research also explores the relationship between pro bono and clinical legal education undertaken by universities and its role in enhancing the employability of law students looking to enter the legal profession.",
    firm: "University of Birmingham",
    sentEmailsTime: [],
  },
  {
    name: "Samantha",
    surname: "Schnobel",
    email: "s.schnobel@bham.ac.uk",
    linkedin: "",
    comment:
      "Deputy Head of Education (Specialised Programmes). Samantha’s primary teaching and research interests lie in the fields of tort and professional ethics, specifically those areas which bear upon the construction of human and nonhuman health-related negligence claims.",
    firm: "University of Birmingham",
    sentEmailsTime: [],
  },
  {
    name: "Argyro",
    surname: "Karanasiou",
    email: "a.karanasiou@bham.ac.uk",
    linkedin: "",
    comment:
      "Dr Karanasiou’s research focusses on the relationship between Law and Emerging Technologies and falls within three general lines of work:  1. Data Governance, 2. Legal Tech and law computability, and 3. Regulating mixed interfaces (Human-Computer Interactions). Al. Argyro’s work is contributing to the growing body of ‘law and emerging technologies’ transdisciplinary scholarship and has earned her visiting research affiliations with Yale Law School (ISP Alumna), NYU Law (ILI Alumna), Harvard Law (affiliate Faculty staff CopyX), Complutense Madrid (ITC). Her research spans a wide range of areas ranging from wearable tech and regulation of health data to Brain-Machine-Interfaces and embodiment, which all share a common underlying theme of re-conceptualisation of autonomy in an era of rapid automation.",
    firm: "University of Birmingham",
    sentEmailsTime: [],
  },
  {
    name: "Richard",
    surname: "Kirkham",
    email: "R.M.Kirkham@sheffield.ac.uk",
    linkedin: "",
    comment:
      "Head of School. I received a Teaching Excellence Award in 2015 in recognition of sustained high quality teaching, various examples of innovative teaching and best practice in the School of Law, and for my work in leading the review of our undergraduate qualifying law degrees.",
    firm: "University of Sheffield",
    sentEmailsTime: [],
  },
  {
    name: "Graham",
    surname: "Gee",
    email: "G.Gee@sheffield.ac.uk",
    linkedin: "",
    comment: "Faculty Director of Education",
    firm: "University of Sheffield",
    sentEmailsTime: [],
  },
  {
    name: "Catherine",
    surname: "Easton",
    email: "c.easton@lancaster.ac.uk",
    linkedin: "",
    comment:
      "Dr Easton also carries out research on teaching law with technology. Head of School. Professor in Information Technology Law and Intellectual Property. Dr Easton's research interests focus upon internet governance, domain name regulation, intellectual property, access to technology and human/computer interaction.",
    firm: "Lancaster University law",
    sentEmailsTime: [],
  },
  {
    name: "Michael",
    surname: "Doherty",
    email: "m.doherty@lancaster.ac.uk",
    linkedin: "",
    comment:
      "His current research and pedagogy focus is in the developing field of legal design - applying design thinking to legal problems and processes. He is exploring the disciplinarity of, and the cultural barriers to, bringing design thinking into law, and has applied design thinking to legal teaching and curriculum development. Associate Head of School (Student Experience)",
    firm: "Lancaster University law",
    sentEmailsTime: [],
  },
  {
    name: "Benjamin",
    surname: "Mayfield",
    email: "",
    linkedin:
      "https://www.linkedin.com/in/ben-mayfield-881087108/?originalSubdomain=uk",
    comment:
      "LLB Law Programme Leader. Projects. Activities. PhD Students. Research Groups. The Law School Skills Project - Stage 1. 01/10/2022 → 31/12/2023. Research. http://www.research.lancs.ac.uk/portal/en/upmprojects/the-law-school-skills-project--stage-1(b8dadd47-dee7-4554-86ed-4ab934eadb04).html",
    firm: "Lancaster University law",
    sentEmailsTime: [],
  },
  {
    name: "Tina",
    surname: "McKee",
    email: "t.mckee1@lancaster.ac.uk",
    linkedin: "",
    comment:
      "Director of Skills and Widening Participation, Law School, Senior Lecturer in Law (Legal Education). Tina's scholarship interests are in skills development; widening participation; equality, diversity and inclusion; decolonising the curriculum; and legal education.",
    firm: "Lancaster University law",
    sentEmailsTime: [],
  },
  {
    name: "Dalia",
    surname: "Aizi",
    email: "dalia.aizi@ncl.ac.uk",
    linkedin: "",
    comment: "Student Experience/Engagement Officer",
    firm: "Newcastle University",
    sentEmailsTime: [],
  },
  {
    name: "Jonathan",
    surname: "Galloway",
    email: "jonathan.galloway@ncl.ac.uk",
    linkedin: "",
    comment:
      "Head of School. Jonathan's Faculty Internationalisation remit included developing and supporting the implementation of the University Global Strategy within the HaSS Faculty, leading on the University’s (international) mobility plan, being a principal point of contact for several institutional international partners, as well as assisting in the identification of emerging student recruitment markets, supporting Brexit mobility contingency planning and on the large scale repatriation of students at the early stages of the Covid-19 pandemic. Estates strategy responsibilities included supporting capital projects management and user engagement within the Faculty, supporting estates and space strategic planning, and ensuring that our University facilities met our research and educational needs.",
    firm: "Newcastle University",
    sentEmailsTime: [],
  },
  {
    name: "Ilke",
    surname: "Turkmendag",
    email: "ilke.turkmendag@ncl.ac.uk",
    linkedin: "",
    comment: "Senior Lecturer in Law, Innovation, and Society",
    firm: "Newcastle University",
    sentEmailsTime: [],
  },
  {
    name: "Valsamis",
    surname: "Mitsilegas",
    email: "V.Mitsilegas@liverpool.ac.uk",
    linkedin: "",
    comment:
      "Dean, School of Law and Social Justice & Professor of European and Global Law",
    firm: "University of Liverpool",
    sentEmailsTime: [],
  },
  {
    name: "Helen",
    surname: "Stalford",
    email: "Stalford@liverpool.ac.uk",
    linkedin: "",
    comment:
      "Head of Department (Law) / Personal Chair. Helen is a founding member of the European Children's Rights Unit (ECRU). She established and continues to run the University of Liverpool's Young Person's Advisory Group, and co-ordinates research collaborations, methods and ethics exchange as Faculty theme lead for Children and Childhood.",
    firm: "University of Liverpool",
    sentEmailsTime: [],
  },
  {
    name: "Lucy",
    surname: "Yeatman",
    email: "Lucy.Yeatman@liverpool.ac.uk",
    linkedin: "",
    comment:
      "Director, Law Clinic. Lucy Yeatman is a senior lecturer in law and a practicing solicitor specialising in family law in the Liverpool Law Clinic. She is passionate about clinical legal education and has extensive experience of designing and delivering clinical legal education programmes.",
    firm: "University of Liverpool",
    sentEmailsTime: [],
  },
  {
    name: "Paul",
    surname: "Bernal",
    email: "Paul.Bernal@uea.ac.uk",
    linkedin: "",
    comment:
      "School of Law - Professor of Information Technology Law.  His first degree was in mathematics, at Cambridge University, over 35 years ago, and he is a qualified Chartered Accountant. For over 20 years he worked as an auditor, in finance for big companies in the City, done pioneering work in the early days of the internet, including setting up and running the first online real-time education system for children to operate in the UK, and been finance director of a charity dealing with mental health and criminal justice.",
    firm: "University of East Anglia UEA",
    sentEmailsTime: [],
  },
  {
    name: "Andreas",
    surname: "Stephan",
    email: "A.Stephan@uea.ac.uk",
    linkedin: "",
    comment: "Professor of Competition Law & Head of School",
    firm: "University of East Anglia UEA",
    sentEmailsTime: [],
  },
  {
    name: "Elias",
    surname: "Deutscher",
    email: "E.Deutscher@uea.ac.uk",
    linkedin: "",
    comment:
      "Elias Deutscher is a Lecturer in Competition Law and IP at the UEA Law School and a member of the Centre for Competition Policy (CCP). Elias holds a Postgraduate Certificate in Higher Education Practice (PGCERT) and is a Fellow of the Higher Education Academy",
    firm: "University of East Anglia UEA",
    sentEmailsTime: [],
  },
  {
    name: "Jonathan",
    surname: "Fortnam",
    email: "j.fortnam@aston.ac.uk",
    linkedin: "",
    comment:
      "Research interest: The Future of Law. Dean of Aston Law School. Jonathan is committed to innovation in the legal sector and for Aston law graduates to be ‘future ready’ citizens and professionals, ready to make a valued contribution to their communities. ",
    firm: "Aston University, Birmingham",
    sentEmailsTime: [],
  },
  {
    name: "Kristie",
    surname: "Thomas",
    email: "k.thomas5@aston.ac.uk ",
    linkedin: "",
    comment:
      "Deputy Head of School. Her current research interests combine elements of law and business, reflecting her research interests in international trade, intellectual property, comparative law and business practice more generally.",
    firm: "Aston University, Birmingham",
    sentEmailsTime: [],
  },
  {
    name: "Christopher",
    surname: "Umfreville",
    email: "c.umfreville@aston.ac.uk",
    linkedin: "",
    comment:
      "Senior Lecturer and Associate Dean - Education. Additionally, Chris is the Learning and Teaching Convenor for Aston Law School and co-chair of the organising committee for the Association of Law Teachers' 2021 Annual Conference at Aston University.",
    firm: "Aston University, Birmingham",
    sentEmailsTime: [],
  },
  {
    name: "Jo",
    surname: "Wilson",
    email: "J.L.Wilson@sussex.ac.uk",
    linkedin: "",
    comment:
      "Senior Lecturer in Commercial Law (Law). School of Law, Politics and Sociology. Jo moved to an Education and Scholarship contract in September 2020 so that she could pursue research in the field of legal education and pedagogy. Jo has since worked on a number of projects including authentic learning and optionality in assessment, and she has co-founded 'Contract Ed Talk', a national network for academics who teach contract law. ",
    firm: "University of Sussex",
    sentEmailsTime: [],
  },
  {
    name: "Amir",
    surname: "Paz-Fuchs",
    email: "A.Paz-Fuchs@sussex.ac.uk",
    linkedin: "",
    comment: "Head of Department",
    firm: "University of Sussex",
    sentEmailsTime: [],
  },
  {
    name: "Melanie",
    surname: "Hart-Murison",
    email: "M.H-Murison@sussex.ac.uk",
    linkedin: "",
    comment: "Senior Clinical Legal Education Coordinator",
    firm: "University of Sussex",
    sentEmailsTime: [],
  },
  {
    name: "Eddie",
    surname: "Bruce-Jones",
    email: "eb55@soas.ac.uk",
    linkedin: "",
    comment:
      "School of Law Head of School. BIO: https://www.soas.ac.uk/about/eddie-bruce-jones",
    firm: "SOAS University of London",
    sentEmailsTime: [],
  },
  {
    name: "Sally",
    surname: "Kyd",
    email: "sally.kyd@leicester.ac.uk",
    linkedin: "",
    comment:
      "Head of Leicester Law School. I am an expert in Criminal Law, with my main specialism being in road traffic offences. My interest in this field originates from my PhD on vehicular homicide (awarded by the University of Leicester in 2004), after which my interest broadened and I developed my knowledge to become the leading legal academic in road traffic offences in the UK. I have spent the majority of my career at Leicester, and was honoured to be appointed the first female Head of School, having been both an undergraduate and graduate student here. ",
    firm: "University of Leicester",
    sentEmailsTime: [],
  },
  {
    name: "Anthony",
    surname: "Berry",
    email: "anthony.berry@le.ac.uk",
    linkedin: "",
    comment: "Digital, Learning Technologies, IT, and Web Manager.",
    firm: "University of Leicester",
    sentEmailsTime: [],
  },
  {
    name: "Natalie",
    surname: "Corkill",
    email: "natalie.corkill@le.ac.uk",
    linkedin: "",
    comment: "Digital, Learning Technologies, IT, and Web ",
    firm: "University of Leicester",
    sentEmailsTime: [],
  },
  {
    name: "Jenny",
    surname: "Chapman",
    email: "jenny.chapman@ntu.ac.uk",
    linkedin: "",
    comment:
      "Executive Dean. Jenny maintains an active research interest in the role of clinical legal education and the area of Alternative Business Structures and their place within a legal education environment.",
    firm: "Nottingham Trent University",
    sentEmailsTime: [],
  },
  {
    name: "Matthew",
    surname: "Homewood",
    email: "matthew.homewood@ntu.ac.uk",
    linkedin: "",
    comment:
      "Deputy Dean. Matthew is Deputy Dean and Associate Professor at Nottingham Law School. Matthew was awarded a National Teaching Fellowship in 2016, the most prestigious individual award for excellence in teaching in higher education. This was in recognition for his use of technology and making a real difference to the student experience. Matthew is an active member of the following research centres, societies and committees:Centre for Legal Education Innovation and Technology Law Lab Society of Legal Scholars Global Legal Skills Programme Committee Global Legal Skills Conference Committee Fusion Steering Committee 2014-2019 Association of Learning Technologists",
    firm: "Nottingham Trent University",
    sentEmailsTime: [],
  },
  {
    name: "Elyse",
    surname: "Wakelin",
    email: "elyse.wakelin02@ntu.ac.uk",
    linkedin: "",
    comment:
      "Head of Department. Elyse Wakelin is the Head of Undergraduate Programmes for Nottingham Law School, with strategic oversight of the Undergraduate portfolio. Elyse is also an active member of the Centre for Legal Education. Elyse is an active member of the Nottingham Law School Centre for Legal Education. Her research focuses primarily on the wellbeing of students in legal education and ways to enhance the student experience. Recent projects have included analysing the role of the personal tutor in legal education. She is currently starting a project which examines wellbeing among distance learning law students.",
    firm: "Nottingham Trent University",
    sentEmailsTime: [],
  },
  {
    name: "Alexandra",
    surname: "Kastrinou",
    email: "alexandra.kastrinou@ntu.ac.uk",
    linkedin: "",
    comment:
      "Alex is the Head of Postgraduate Portfolio at Nottingham Law School, encompassing the Legal Practice Course, the Barristers Training Course, the Postgraduate Diploma in Law and the Academic Masters.",
    firm: "Nottingham Trent University",
    sentEmailsTime: [],
  },
  {
    name: "Laura",
    surname: "Pinkney",
    email: "laura.pinkney@ntu.ac.uk",
    linkedin: "",
    comment:
      "Head of Department. Laura is Head of the NLS Legal, a teaching law firm, based within the Chaucer building. The firm is fully regulated as an alternative business structure by the Solicitors Regulation Authority. The firm plays a vital role in inspiring the next generation of legal professionals and provides Nottingham Law School students with unique opportunities to develop their technical and practical skills. The firm also provides access to justice to those who are unable to afford or access much needed legal advice. The firm works closely with local firms, advice agencies, voluntary sector organisations and schools to offer legal support to the local community and develop pro bono opportunities for Nottingham Law School students. ",
    firm: "Nottingham Trent University",
    sentEmailsTime: [],
  },
  //   {
  //     name: "",
  //     surname: "",
  //     email: "",
  //     linkedin: "",
  //     comment: "",
  //     firm: "",
  //     sentEmailsTime: [],
  //   },
  //   {
  //     name: "",
  //     surname: "",
  //     email: "",
  //     linkedin: "",
  //     comment: "",
  //     firm: "",
  //     sentEmailsTime: [],
  //   },
  //   {
  //     name: "",
  //     surname: "",
  //     email: "",
  //     linkedin: "",
  //     comment: "",
  //     firm: "",
  //     sentEmailsTime: [],
  //   },
  //   {
  //     name: "",
  //     surname: "",
  //     email: "",
  //     linkedin: "",
  //     comment: "",
  //     firm: "",
  //     sentEmailsTime: [],
  //   },
  //   {
  //     name: "",
  //     surname: "",
  //     email: "",
  //     linkedin: "",
  //     comment: "",
  //     firm: "",
  //     sentEmailsTime: [],
  //   },
  //   {
  //     name: "",
  //     surname: "",
  //     email: "",
  //     linkedin: "",
  //     comment: "",
  //     firm: "",
  //     sentEmailsTime: [],
  //   },
  //   {
  //     name: "",
  //     surname: "",
  //     email: "",
  //     linkedin: "",
  //     comment: "",
  //     firm: "",
  //     sentEmailsTime: [],
  //   },
  //   {
  //     name: "",
  //     surname: "",
  //     email: "",
  //     linkedin: "",
  //     comment: "",
  //     firm: "",
  //     sentEmailsTime: [],
  //   },
  //   {
  //     name: "",
  //     surname: "",
  //     email: "",
  //     linkedin: "",
  //     comment: "",
  //     firm: "",
  //     sentEmailsTime: [],
  //   },
  //   {
  //     name: "",
  //     surname: "",
  //     email: "",
  //     linkedin: "",
  //     comment: "",
  //     firm: "",
  //     sentEmailsTime: [],
  //   },
  //   {
  //     name: "",
  //     surname: "",
  //     email: "",
  //     linkedin: "",
  //     comment: "",
  //     firm: "",
  //     sentEmailsTime: [],
  //   },
  //   {
  //     name: "",
  //     surname: "",
  //     email: "",
  //     linkedin: "",
  //     comment: "",
  //     firm: "",
  //     sentEmailsTime: [],
  //   },
  //   {
  //     name: "",
  //     surname: "",
  //     email: "",
  //     linkedin: "",
  //     comment: "",
  //     firm: "",
  //     sentEmailsTime: [],
  //   },
  //   {
  //     name: "",
  //     surname: "",
  //     email: "",
  //     linkedin: "",
  //     comment: "",
  //     firm: "",
  //     sentEmailsTime: [],
  //   },
  //   {
  //     name: "",
  //     surname: "",
  //     email: "",
  //     linkedin: "",
  //     comment: "",
  //     firm: "",
  //     sentEmailsTime: [],
  //   },
  //   {
  //     name: "",
  //     surname: "",
  //     email: "",
  //     linkedin: "",
  //     comment: "",
  //     firm: "",
  //     sentEmailsTime: [],
  //   },
  //   {
  //     name: "",
  //     surname: "",
  //     email: "",
  //     linkedin: "",
  //     comment: "",
  //     firm: "",
  //     sentEmailsTime: [],
  //   },
];

console.log("emailList", emailList.length);
